site01/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/profile'

  get 'home/about_us'

  get 'home/galley'

  get 'home/help'

  get 'home/contact_us'

  devise_for :users

  root :to => 'home#index'

end

site01/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  validates :first_name,  presence: true, length: { maximum: 15 }
  validates :last_name,  presence: true, length: { maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  #validates :password, presence: true, length: { minimum: 4 }
  #validates :password_confirmation, presence: true
  validates :password, :format => {:with => /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{4,}/, message: "Password must be at least 4 characters and include one number and one letter."}
  
  has_attached_file :avatar, styles: { large: "600x600>" , medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_attachment :avatar, :presence => true, :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }, :size => { :in => 0..1.megabytes }
end

site01/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :date_of_birth, :is_femaile, :email, :password, :password_confirmation, :avatar)}
  	
  	devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:first_name, :last_name, :date_of_birth, :is_femaile, :email, :password, :password_confirmation, :current_password, :avatar)}

  end
  
end

site01/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def profile
  end

  def about_us
  end

  def galley
  end

  def help
  end

  def contact_us
  end
end

site01/app/helpers/home_helper.rb
module HomeHelper
end

site01/app/views/home/about_us.html.erb
<div class ="container">
	<div class="row">
		<h3 class="heading">About us</h3>
		<p>lubwils family......
		.........<%= link_to "Contact Us", home_contact_us_path%></p>
		<br>
		
	</div>
	<div class="col-md-5">
		<%= image_tag("rosesred.jpg", :alt => "rosesred", :class => "about-image" ) %>
		
	</div>
	<div class="row">
		<div class="col-md-12">
			<h3> our services</h3>
		</div>
	</div>
	
</div>

site01/app/views/home/contact_us.html.erb
<h1>Contact us page</h1>

site01/app/views/home/galley.html.erb
<h1>Gallery Page</h1>

site01/app/views/home/help.html.erb
<h1>Help page</h1>

site01/app/views/home/index.html.erb
<div class="container">
	<div class="row">

		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= image_tag("attractive-green-rose-wallpaper-normal.jpg", :alt => "attractive-green-rose-wallpaper-normal" ) %>
			</div>
			
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= image_tag("rosesred.jpg", :alt => "rosesred" ) %>
			</div>
			
		</div>
		
	</div>
</div>

site01/app/views/home/profile.html.erb
<h1>Profile page</h1>
	
	<% if current_user %>
		<li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
		
	<% else %>
	<li><%= link_to 'Login', new_user_session_path %></li>
	<% end %>

site01/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lubwils-family</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
	<div class ="container">
		<div class ="nav">
			<ul class ="nav nav-tabs">
			<li><%= link_to 'Home', home_index_path %></li>
			<li><%= link_to 'About Us', home_about_us_path %></li>
			<li><%= link_to 'Contact Us', home_contact_us_path %></li>
			<li><%= link_to 'help?', home_help_path %></li>
			<% if user_signed_in? %>
			<li><%= link_to 'Profile', home_profile_path %></li>
			<li><%= link_to 'Gallery', home_galley_path %></li><li>Logged in as <strong><%= current_user.email%></strong></li>
			<li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

			<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %>
			<% else %>
			<li><%= link_to 'Login', new_user_session_path %></li>
			<li><%= link_to 'SignUp', new_user_registration_path%></li>

			<% end %>
			
			</ul>
		</div>
	</div>
	
	
<%= yield %>
<div class="modal-footer">
	<p>@copyright 2015 <%= link_to "terms & condtions", "#"%></p>
	
</div>
</body>
</html>