video_upload/config/routes.rb
Rails.application.routes.draw do
  get 'video_controller/index'

  get 'video_controller/new'

  get '/auth/:provider/callback', to: 'sessions#create' #/auth/:provider/callback route is the callback where the user is redirected after successful authentication

  get '/auth/failure', to: 'sessions#fail' #used when an error occurrs during the authentication phase.

  get '/videos/get_video_uid', to: 'videos#get_video_uid', as: :get_video_uid

  post '/videos/get_upload_token', to: 'videos#get_upload_token', as: :get_upload_token

  resources :video_controller, only: [:new, :index]

  root to: 'video_controller#index'

end

video_upload/app/models/user.rb
class User < ActiveRecord::Base
	has_many :videos
end

video_upload/app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

video_upload/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
 
	def current_user
	  @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
	end
	 
	helper_method :current_user
	  
end

video_upload/app/controllers/session_controller.rb
class SessionController < ApplicationController
	def create
	    auth = request.env['omniauth.auth']
	    user = User.find_or_initialize_by(uid: auth['uid'])
	    user.token = auth['credentials']['token']
	    user.name = auth['info']['name']
	    user.save
	    session[:user_id] = user.id
	    flash[:success] = "Welcome, #{user.name}!"
	    redirect_to new_video_path
	end
 
	 def fail
	    render text: "Sorry, but the following error has occured: #{params[:message]}. Please try again or contact administrator."
	 end
end

video_upload/app/controllers/video_controller_controller.rb
class VideoControllerController < ApplicationController
  def index
  	@videos = Video.all
  end

  def new
  	@pre_upload_info = {}
  end

  def get_upload_token
  temp_params = { title: params[:title], description: params[:description], category: 'Education',
                  keywords: [] }
 
  if current_user
	    codefellowship = YouTubeIt::OAuth2Client.new(client_access_token: current_user.token,
	                                          dev_key: ENV['AIzaSyDVtfCp87NQnBgSlk0y8J0X7moqSTKvaCQ'])
	 
	    upload_info = codefellowship.upload_token(temp_params, get_video_uid_url)
	 
	    render json: {token: upload_info[:token], url: upload_info[:url]}
	  else
	    render json: {error_type: 'Not authorized.', status: :unprocessable_entity}
	  end
	end

  	def get_video_uid
		  video_uid = params[:id]
		  v = current_user.videos.build(uid: video_uid)
		  codefellowship = YouTubeIt::OAuth2Client.new(dev_key: ENV['AIzaSyDVtfCp87NQnBgSlk0y8J0X7moqSTKvaCQ'])
		  yt_video = codefellowship.video_by(video_uid)
		  v.title = yt_video.title
		  v.description = yt_video.description
		  v.save
		  flash[:success] = 'Thanks for sharing your video!'
		  redirect_to root_url
	end

end

video_upload/app/helpers/application_helper.rb
module ApplicationHelper
end

video_upload/app/helpers/session_helper.rb
module SessionHelper
end

video_upload/app/helpers/video_controller_helper.rb
module VideoControllerHelper
end

video_upload/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoUpload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'pod Uploader', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Videos', root_path %></li>
        <li><%= link_to 'Add Video', new_video_controller_path %></li>
      </ul>
    </div>
  </div>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

video_upload/app/views/video_controller/_form.html.erb
<%= form_tag '', id: 'video_pre_upload' do %>
  <div class="form-group">
    <%= text_field_tag :title, @pre_upload_info[:title], required: true,placeholder: 'Title', class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= text_area_tag :description, @pre_upload_info[:description], required: true, placeholder: 'Description', class: 'form-control' %>
  </div>
<% end %>
 
<%= form_tag '', id: 'video_upload', multipart: true do %>
  <%= hidden_field_tag :token, '' %>
 
  <div class="form-group">
    <%= file_field_tag :file, required: true %>
  </div>
<% end %>
 
<button id="submit_pre_upload_form" class="btn btn-lg btn-primary">Upload</button>
<%= image_tag 'ajax-loader.gif', class: 'preloader', alt: 'Uploading...', title: 'Uploading...' %>

<script>
  $(document).ready(function() {
    var submit_button = $('#submit_pre_upload_form');
    var video_upload = $('#video_upload');
    submit_button.click(function () {
      $.ajax({
        type: 'POST',
        url: '<%= get_upload_token_path %>',
        data: $('#video_pre_upload').serialize(),
        dataType: 'json',
        success: function(response) {
          video_upload.find('#token').val(response.token);
          video_upload.attr('action', response.url.replace(/^http:/i, window.location.protocol)).submit();
          submit_button.unbind('click').hide();
          $('.preloader').css('display', 'block');
        }
      });
    });
  });
</script>

video_upload/app/views/video_controller/index.html.erb
<div class="jumbotron">
  <h1>Code Fellowship podcast Uploader</h1>
  <p>Upload your video to CodeFellowship podcast and share it with the world!</p>
  <p><%= link_to 'Upload video now!', new_video_controller_path, class: 'btn btn-primary btn-lg' %></p>
</div>

<div class="page-header">
  <h1>Videos</h1>
</div>
 
<ul class="row" id="videos-list">
  <% @videos.each do |video| %>
    <li class="col-sm-3">
      <div class="thumbnail">
        <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                              class: 'img-rounded'),
                    "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
 
        <div class="caption">
          <h4><%= video.title %></h4>
          <p><%= truncate video.description, length: 100 %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

video_upload/app/views/video_controller/new.html.erb
<div class="page-header">
  <h1>Upload Video</h1>
</div>
<% if current_user %>
	 <% render 'form' %>
 <% else %>
	<p>Please <%= link_to 'authorize', '/auth/google_oauth2' %> via your Google account to continue.</p>
<% end %>